package ca.concordia.encs.distributed.client.corba.model;

/**
* ca/concordia/encs/distributed/client/corba/model/ClinicServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ClinicServices.idl
* Monday, July 4, 2016 5:06:05 PM CDT
*/

public final class ClinicServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public ca.concordia.encs.distributed.client.corba.model.ClinicService value = null;

  public ClinicServiceHolder ()
  {
  }

  public ClinicServiceHolder (ca.concordia.encs.distributed.client.corba.model.ClinicService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ca.concordia.encs.distributed.client.corba.model.ClinicServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ca.concordia.encs.distributed.client.corba.model.ClinicServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ca.concordia.encs.distributed.client.corba.model.ClinicServiceHelper.type ();
  }

}
