package ca.concordia.encs.distributed.client.corba.model;


/**
* ca/concordia/encs/distributed/client/corba/model/ClinicService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ClinicServices.idl
* Monday, July 4, 2016 5:06:05 PM CDT
*/

public interface ClinicService extends ClinicServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ClinicService
