package ca.concordia.encs.distributed.corba.model;


/**
* ca/concordia/encs/distributed/corba/model/ClinicServicePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ClinicServices.idl
* Monday, July 4, 2016 11:59:07 AM CDT
*/

public abstract class ClinicServicePOA extends org.omg.PortableServer.Servant
 implements ca.concordia.encs.distributed.corba.model.ClinicServiceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("createDRecord", new java.lang.Integer (0));
    _methods.put ("createNRecord", new java.lang.Integer (1));
    _methods.put ("getRecordCounts", new java.lang.Integer (2));
    _methods.put ("editRecord", new java.lang.Integer (3));
    _methods.put ("transferRecord", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // interop/ClinicService/createDRecord
       {
         String managerID = in.read_string ();
         String firstName = in.read_string ();
         String lastName = in.read_string ();
         String address = in.read_string ();
         String phone = in.read_string ();
         String specialization = in.read_string ();
         ca.concordia.encs.distributed.corba.model.Message $result = null;
         $result = this.createDRecord (managerID, firstName, lastName, address, phone, specialization);
         out = $rh.createReply();
         ca.concordia.encs.distributed.corba.model.MessageHelper.write (out, $result);
         break;
       }

       case 1:  // interop/ClinicService/createNRecord
       {
         String managerID = in.read_string ();
         String firstName = in.read_string ();
         String lastName = in.read_string ();
         String designation = in.read_string ();
         String status = in.read_string ();
         int statusDate = in.read_long ();
         ca.concordia.encs.distributed.corba.model.Message $result = null;
         $result = this.createNRecord (managerID, firstName, lastName, designation, status, statusDate);
         out = $rh.createReply();
         ca.concordia.encs.distributed.corba.model.MessageHelper.write (out, $result);
         break;
       }

       case 2:  // interop/ClinicService/getRecordCounts
       {
         String managerID = in.read_string ();
         String recordType = in.read_string ();
         ca.concordia.encs.distributed.corba.model.Message $result = null;
         $result = this.getRecordCounts (managerID, recordType);
         out = $rh.createReply();
         ca.concordia.encs.distributed.corba.model.MessageHelper.write (out, $result);
         break;
       }

       case 3:  // interop/ClinicService/editRecord
       {
         String managerID = in.read_string ();
         String recordID = in.read_string ();
         String fieldName = in.read_string ();
         String newValue = in.read_string ();
         ca.concordia.encs.distributed.corba.model.Message $result = null;
         $result = this.editRecord (managerID, recordID, fieldName, newValue);
         out = $rh.createReply();
         ca.concordia.encs.distributed.corba.model.MessageHelper.write (out, $result);
         break;
       }

       case 4:  // interop/ClinicService/transferRecord
       {
         String managerID = in.read_string ();
         String recordID = in.read_string ();
         String remoteClinicServerName = in.read_string ();
         ca.concordia.encs.distributed.corba.model.Message $result = null;
         $result = this.transferRecord (managerID, recordID, remoteClinicServerName);
         out = $rh.createReply();
         ca.concordia.encs.distributed.corba.model.MessageHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:interop/ClinicService:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ClinicService _this() 
  {
    return ClinicServiceHelper.narrow(
    super._this_object());
  }

  public ClinicService _this(org.omg.CORBA.ORB orb) 
  {
    return ClinicServiceHelper.narrow(
    super._this_object(orb));
  }


} // class ClinicServicePOA
