package ca.concordia.encs.distributed.corba.model;


/**
* ca/concordia/encs/distributed/corba/model/ClinicServicePOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ClinicServices.idl
* Monday, July 4, 2016 11:59:07 AM CDT
*/

public class ClinicServicePOATie extends ClinicServicePOA
{

  // Constructors

  public ClinicServicePOATie ( ca.concordia.encs.distributed.corba.model.ClinicServiceOperations delegate ) {
      this._impl = delegate;
  }
  public ClinicServicePOATie ( ca.concordia.encs.distributed.corba.model.ClinicServiceOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public ca.concordia.encs.distributed.corba.model.ClinicServiceOperations _delegate() {
      return this._impl;
  }
  public void _delegate (ca.concordia.encs.distributed.corba.model.ClinicServiceOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public ca.concordia.encs.distributed.corba.model.Message createDRecord (String managerID, String firstName, String lastName, String address, String phone, String specialization)
  {
    return _impl.createDRecord(managerID, firstName, lastName, address, phone, specialization);
  } // createDRecord

  public ca.concordia.encs.distributed.corba.model.Message createNRecord (String managerID, String firstName, String lastName, String designation, String status, int statusDate)
  {
    return _impl.createNRecord(managerID, firstName, lastName, designation, status, statusDate);
  } // createNRecord

  public ca.concordia.encs.distributed.corba.model.Message getRecordCounts (String managerID, String recordType)
  {
    return _impl.getRecordCounts(managerID, recordType);
  } // getRecordCounts

  public ca.concordia.encs.distributed.corba.model.Message editRecord (String managerID, String recordID, String fieldName, String newValue)
  {
    return _impl.editRecord(managerID, recordID, fieldName, newValue);
  } // editRecord

  public ca.concordia.encs.distributed.corba.model.Message transferRecord (String managerID, String recordID, String remoteClinicServerName)
  {
    return _impl.transferRecord(managerID, recordID, remoteClinicServerName);
  } // transferRecord

  private ca.concordia.encs.distributed.corba.model.ClinicServiceOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class ClinicServicePOATie
