package ca.concordia.encs.distributed.corba.model;


/**
* ca/concordia/encs/distributed/corba/model/ClinicServiceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ClinicServices.idl
* Monday, July 4, 2016 11:59:07 AM CDT
*/

abstract public class ClinicServiceHelper
{
  private static String  _id = "IDL:interop/ClinicService:1.0";

  public static void insert (org.omg.CORBA.Any a, ca.concordia.encs.distributed.corba.model.ClinicService that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ca.concordia.encs.distributed.corba.model.ClinicService extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (ca.concordia.encs.distributed.corba.model.ClinicServiceHelper.id (), "ClinicService");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ca.concordia.encs.distributed.corba.model.ClinicService read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ClinicServiceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ca.concordia.encs.distributed.corba.model.ClinicService value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static ca.concordia.encs.distributed.corba.model.ClinicService narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ca.concordia.encs.distributed.corba.model.ClinicService)
      return (ca.concordia.encs.distributed.corba.model.ClinicService)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ca.concordia.encs.distributed.corba.model._ClinicServiceStub stub = new ca.concordia.encs.distributed.corba.model._ClinicServiceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static ca.concordia.encs.distributed.corba.model.ClinicService unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ca.concordia.encs.distributed.corba.model.ClinicService)
      return (ca.concordia.encs.distributed.corba.model.ClinicService)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ca.concordia.encs.distributed.corba.model._ClinicServiceStub stub = new ca.concordia.encs.distributed.corba.model._ClinicServiceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
