package ca.concordia.encs.distributed.corba.model;


/**
* ca/concordia/encs/distributed/corba/model/Message.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ClinicServices.idl
* Monday, July 4, 2016 11:59:07 AM CDT
*/

public final class Message implements org.omg.CORBA.portable.IDLEntity
{
  public String Method = null;
  public short Status = (short)0;
  public String Content = null;

  public Message ()
  {
  } // ctor

  public Message (String _Method, short _Status, String _Content)
  {
    Method = _Method;
    Status = _Status;
    Content = _Content;
  } // ctor

} // class Message
