package ca.concordia.encs.distributed.corba.model;

/**
* ca/concordia/encs/distributed/corba/model/MessageHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ClinicServices.idl
* Monday, July 4, 2016 11:59:07 AM CDT
*/

public final class MessageHolder implements org.omg.CORBA.portable.Streamable
{
  public ca.concordia.encs.distributed.corba.model.Message value = null;

  public MessageHolder ()
  {
  }

  public MessageHolder (ca.concordia.encs.distributed.corba.model.Message initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ca.concordia.encs.distributed.corba.model.MessageHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ca.concordia.encs.distributed.corba.model.MessageHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ca.concordia.encs.distributed.corba.model.MessageHelper.type ();
  }

}
